import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ButtonPay from '@google-pay/button-react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <div className='container w-1/2 mx-auto my-2 flex flex-col gap-y-5'>
        <div className='w-auto mx-auto grid '>
          <img className='w-1/2 place-self-center' src="tshirt.jpg" alt="logo" title="placeholder" />
        </div>

        <div className=''>
          <p className='text-lg font-helvetica'>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui repellendus a laudantium doloremque accusamus, iure eaque quisquam consequuntur earum perferendis et obcaecati, quia quo! Voluptatem ducimus harum ipsa eum assumenda!
          </p>
        </div>

        <div>

        </div>

        <div className='mx-auto'
          style={{ padding: "1rem 1rem 3.3rem 1rem !important" }}>
          <h1 className='text-2xl pb-5'>
            <span className='text-3xl font-bold border-solid rounded-md border-2 border-sky-300 bg-sky-300 pl-8 pr-8'> $100</span>
          </h1>
          <ButtonPay
            buttonType='buy'
            buttonColor='white'
            environment='TEST'
            paymentRequest={{
              apiVersion: 2,
              apiVersionMinor: 0,
              allowedPaymentMethods: [
                {
                  type: 'CARD',
                  parameters: {
                    allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                    allowedCardNetworks: ['MASTERCARD', 'VISA'],
                    billingAddressRequired: true,
                  },
                  tokenizationSpecification: {
                    type: 'PAYMENT_GATEWAY',
                    parameters: {
                      gateway: 'example',
                      gatewayMerchantId: 'exampleGatewayMerchantId',
                    },
                  },
                },
              ],
              merchantInfo: {
                merchantId: '12345678901234567890',
                merchantName: 'Demo Merchant',
              },
              transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPriceLabel: 'Total',
                totalPrice: '100.00',
                currencyCode: 'USD',
                countryCode: 'US',
              },
            }}
            onLoadPaymentData={(data) => {
              console.log(data)
              // alert("Su")
            }}
          />
        </div>

      </div>


    </div>
  )
}
